[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.buildArgs]
NEXT_PUBLIC_SUPABASE_URL = "${{NEXT_PUBLIC_SUPABASE_URL}}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${{NEXT_PUBLIC_SUPABASE_ANON_KEY}}"
SUPABASE_SERVICE_ROLE_KEY = "${{SUPABASE_SERVICE_ROLE_KEY}}"
RESEND_API_KEY = "${{RESEND_API_KEY}}"
NEXTAUTH_SECRET = "${{NEXTAUTH_SECRET}}"
NEXTAUTH_URL = "${{NEXTAUTH_URL}}"
EMAIL_FROM = "${{EMAIL_FROM}}"
