services:
  - type: web
    name: signals-nextjs
    runtime: node
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: pwd && ls -la && ls -la signals/ && ls -la signals/next-saas-nextjs/ && cd signals/next-saas-nextjs && npm install --verbose && npm run build
    startCommand: cd signals/next-saas-nextjs && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.x
      - key: NPM_CONFIG_PRODUCTION
        value: false